name: Test

on:
  push:
    branches: [master, main]
  pull request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
  
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
  steps: 
  - run: pip install flake8
  - run: flake8 --ignore=E501,E121,E126 .