name: Pipeline VictoriaCinemaBot

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install flake8
    - name: Run Unit Tests and generate coverage report
      run: |
          flake8 --ignore=E501,E121,E126 .
